
model_name: hustvl/yolos-small

dataset_dir: dataset/data/
label_path: dataset/label.xml
checkpoint_dir: checkpoints/

epochs: 10
batch_size: 16
learning_rate: 0.001
device: cpu

image_size: 
  - 416
  - 416