
model_name: hustvl/yolos-small

dataset_dir: dataset/參賽者訓練資料集下載(10000)/
label_path: dataset/dataset_10000_update_0912.xml
checkpoint_dir: checkpoints/

epochs: 10
batch_size: 16
learning_rate: 0.001
device: cpu

image_size: 
  - 416
  - 416